# Site settings
title: Data Hub
description: A comprehensive collection of high-resolution datasets for research purposes
baseurl: "/"
url: "https://bippisb.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore
  - README.md

# Custom variables
maintainer:
  name: Gursharan Singh Dhanjal
  team: Data Hub Team
  title: Chief Data Scientist
  organization: Powered By - Bharti Institute of Public Policy, ISB
  email: gursharan_singh@isb.edu